### ISSUE TITLE
Ip jail

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#120]
Store ips of players who leave server during jail time and auto jail them on reconnect for an static default time of around 1 or 2 minutes. Don't save their actual jail time that should be saved in the account.

**Comment by fokkonaut** [comment]
wtf no, thats so stupid

**Comment by ChillerDragon** [comment]
Hm player names would be a idea aswell but it can be bypassed so easy.
Why is it stupid? Because your bro will sent you to jail 24/7? 

get your own vpn :p

**Comment by ChillerDragon** [comment]
We are still open source and security through obscurity is never a good idea.
And for dummy it makes a lot sense. I notice some skilled spawnblocker latly who ripped all players at spawn even tho he had nobo spawn. He was caught by police multiple times but simply reconnected.

The whole server was super annoyed.
