### ISSUE TITLE
Add cfg to disable bodycheck blocks

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#232]
Don't count this as a block if the players only collided.

**Comment by fokkonaut** [comment]
lol, sure. If you punch him down a block

**Comment by ChillerDragon** [comment]
Yes sometimes especially in nobo wayblock you only push him with your body back in freeze. Since hook would be wrong direction and hammer unfreeze. Thats why I decied back then to count this as a block.

But sometimes this is weird especially in battlegores people can accidentally steal kills by just bouncing into each other.

**Comment by fokkonaut** [comment]
then only count body touch if the Other player is grounded

**Comment by ChillerDragon** [comment]
@fokkonaut was thinking about that as well. Maybe both tees have to be grounded? To avoid steals when you fall on a freezed tee and then fail.

This might be the solution that would improve ddnet++ and battlegores gametype and needs no configuration. Im trying to think of a situation where you intentionally block with your body without being grounded. I guess nobody jumps in air to hit a flying tee back into freeze.

I also thought about using y vel to also cover stoppers, lasers and speedups. Or do these count as grounded? Speedups don't but stoppers and lasers might.

**Comment by fokkonaut** [comment]
CCharacter::IsGrounded, yes stopper count as grounded. Lasers do not
