### ISSUE TITLE
Teams crash the server

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#242]
Selfkill after passing startline kills server if you are in a team.

**Comment by ChillerDragon** [comment]
![callstack_teamcrash](https://user-images.githubusercontent.com/20344300/59135231-78f94f00-897e-11e9-8fd2-0f2041d3af9b.png)

Only happens in locked team.

**Comment by fokkonaut** [comment]
I dont know why, but it will kill the team players in a loop until the server crashes
