### ISSUE TITLE
Fix blockwave lag

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#245]
Higher waves cause server lag when the wave starts.

This is probably caused by too many bots joining at the same time. Maybe it is possible to make dummy join more lightweight since they need less stuff than players. No score loading etc.

**Comment by fokkonaut** [comment]
its because of the GetRandomTile() function in collision.cpp

**Comment by ChillerDragon** [comment]
could not reproduce lol?
