### ISSUE TITLE
Add better command to fix broken accounts

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#246]
Sometimes accounts are marked as logged in but they actually aren't. So players can't login. Currently ``/sql_logout_all`` solves this. But this is not a nice solution. Better add a command that gets all logged in players on current port and loggs them out if they are not logged in.

That could even run in a slow tick. But better fix what ever caused these broken accs.

**Comment by fokkonaut** [comment]
./sql_logout <player>

**Comment by ChillerDragon** [comment]
Map change currently breaks accounts. So the logout should maybe happen on the player object destruction or logout all players before map change.

**Comment by ChillerDragon** [comment]
``/sql_logout_all`` should not log out players currently logged in on the server. Adjust the sql query to exclude all ids that are currently used by players.

**Comment by fokkonaut** [comment]
> Map change currently breaks accounts. So the logout should maybe happen on the player object destruction or logout all players before map change.

logout everyone on CServer::LoadMap I guess
