### ISSUE TITLE
Weapon drop bug

### ISSUE THREAD

**Issue by Itube17** [DDNetPP/DDNetPP#333]
Mostly time if u drop ur weapons they get freezed and u can't collect it, only get an sound bug

**Comment by Itube17** [comment]
+add delay for drop weapons and collect weapons

**Comment by ChillerDragon** [comment]
> +add delay for drop weapons and collect weapons

What does that mean?

**Comment by Itube17** [comment]
> > +add delay for drop weapons and collect weapons
> 
> What does that mean?

If you hold F3 for drop weapon it Poops weapons out. Server getting crashed

> sorry for late answer

**Comment by ChillerDragon** [comment]
Should be fixed now. Could you test again.
