### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Filto001** [DDNetPP/DDNetPP#364]
is there an way to use mysql insteade of sqlite?? @ChillerDragon

**Comment by Filto001** [comment]
it only RegisterSqliteDatabase but not RegisterMysqlDatabase

**Comment by ChillerDragon** [comment]
There might not be. I only ever used sqlite and probably also while coding did not bother to support mysql since I do not need it. But yea would be a nice feature.

**Comment by Filto001** [comment]
would it requires big amount of time to change that?

**Comment by ChillerDragon** [comment]
I hope not

**Comment by Filto001** [comment]
:(, maybe could tell my the step to achieve this task?

**Comment by ChillerDragon** [comment]
> :(, maybe could tell my the step to achieve this task?

Compare the ddnet++ sql code to the ddnet sql code and see if you find a missing mysql

**Comment by ChillerDragon** [comment]
> @ChillerDragon would it be possible to get a draft of this ?

I probably won't start working on this for quite some time. Why do you even need it? What do you need MySQL for that sqlite3 can not do?

**Comment by ChillerDragon** [comment]
Okay ddnet++ has now sqlite3 and mysql support similar to ddnet. By default sqlite3 is used. To use mysql you have to compile the server with ``-DMYSQL=ON`` and then add this to your config.

```
sv_use_mysql_for_accounts 1

add_accounts_sqlserver r teeworlds record teeworlds "PW2" "localhost" "3306"
add_accounts_sqlserver w teeworlds record teeworlds "PW2" "localhost" "3306"
```

You need to adapt the values of ``add_accounts_sqlserver`` to fit your database credentials. It has the same format as ddnets ``add_sqlserver`` which is used for race ranks. So you can consult the [ddnet readme](https://github.com/ddnet/ddnet/blob/b710f32a0692696adc22b0ffdf7420d1d5fb2ae0/README.md#importing-the-official-ddnet-database) for more details on how to setup a db.

```
add_accounts_sqlserver s['r'|'w'] s[Database] s[Prefix] s[User] s[Password] s[IP] i[Port] ?i[SetUpDatabase ?]
```
