### ISSUE TITLE
Block wave

### ISSUE THREAD

**Issue by KGriss** [DDNetPP/DDNetPP#37]
What is the blockwave tile ? (Can you make a plan with all tiles and their functions ?)

**Comment by fokkonaut** [comment]
blockwave is a gamemode where you have to block waves of block bots. you can join using /blockwave join. make sure to create a seperate arena with the blcokwave spawn for players (INDEX 128) and some spawns for the bots (index 129)

**Comment by fokkonaut** [comment]
you can also contact  me in discord for more information about the mod. (fokkonaut#5556)
