### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#374]
**EN:** `[ACCOUNT] You are already logged in.`
**RU:**

**EN:** `[ACCOUNT] Logged out.`
**RU:**

**EN:** `[ACCOUNT] Account has been registered.`
**RU:**

**EN:** `[ACCOUNT] Login with: /login <name> <pass>`
**RU:**

**EN:** `[JOIN] Block tournaments are deactivated by an admin.`
**RU:**

**EN:** `[JOIN] No block tournament running.`
**RU:**

**EN:**` [JOIN] You joined a block tournament.`
**RU:**

**EN:** `[JOIN] You already joined the block tournament.`
**RU:**

**Comment by TextesAV** [comment]
Here are the Russian translations:

EN: [ACCOUNT] You are already logged in.
RU: [АККАУНТ] Вы уже вошли в систему.

EN: [ACCOUNT] Logged out.
RU: [АККАУНТ] Вы вышли из системы.

EN: [ACCOUNT] Account has been registered.
RU: [АККАУНТ] Аккаунт зарегистрирован.

EN: [ACCOUNT] Login with: /login <name> <pass>
RU: [АККАУНТ] Войдите с помощью: /login <имя> <пароль>

EN: [JOIN] Block tournaments are deactivated by an admin.
RU: [ПРИСОЕДИНЕНИЕ] Турниры блоков отключены администратором.

EN: [JOIN] No block tournament running.
RU: [ПРИСОЕДИНЕНИЕ] Турнир блоков не проводится.

EN: [JOIN] You joined a block tournament.
RU: [ПРИСОЕДИНЕНИЕ] Вы присоединились к турниру блоков.

EN: [JOIN] You already joined the block tournament.
RU: [ПРИСОЕДИНЕНИЕ] Вы уже присоединились к турниру блоков.

**Comment by ChillerDragon** [comment]
Nice thanks I will add it.

**Comment by TextesAV** [comment]
Maybe new?

**Comment by ChillerDragon** [comment]
> Maybe new?

Enough for today. Pull requests are welcome. But I allocated enough time for translations today.
