### ISSUE TITLE
Translate it again

### ISSUE THREAD

**Issue by TextesAV** [DDNetPP/DDNetPP#375]
EN =  [EVENT] BLOCK IN 5 SECONDS [1/2] /join'ed already
RU= [ИВЕНТ) Блок турнир через (The number of seconds before the tournament) , (The number of people who came in Just a number without /2) зашли. Для того чтобы зайти используй /join

**Comment by ChillerDragon** [comment]
I adapted it to this but it is too long. In general it does not seem to be very smooth.

```
[ИВЕНТ] БЛОК ТУРНИР ЧЕРЕЗ 19
[0/5] Зашли. Для того чтобы зайти используй /jo
```

**Comment by TextesAV** [comment]
EN = [EVENT] BLOCK IN 5 SECONDS [1/2] /join'ed already
RU= [ИВЕНТ) Блок  через 5 сек , 1 человек зашел. Для того чтобы зайти используй /join

**Comment by ChillerDragon** [comment]
> EN = [EVENT] BLOCK IN 5 SECONDS [1/2] /join'ed already RU= [ИВЕНТ) Блок через 5 сек , 1 человек зашел. Для того чтобы зайти используй /join

Its so long and missing a number.

I still like mine better format wise. But not sure if it makes any sense in russian.

```
[ИВЕНТ] БЛОК ТУРНИР ЧЕРЕЗ 5
[1/2] Зашли. Используйте /join
```

**Comment by TextesAV** [comment]
@ChillerDragon your format can be used , but please remove /2 , more than 2 people can still enter

**Comment by ChillerDragon** [comment]
@TextesAV thats the minimum amount of required players to start the tournament. But yes I agree it is not perfect. Not sure how to indicate it better.

**Comment by TextesAV** [comment]
I think people can understand that the tournament will not start when there are only 1 or 0 participants. /2 scares away @ChillerDragon

**Comment by ChillerDragon** [comment]
Yea you are right. I changed it again it now looks like this:

![image](https://github.com/user-attachments/assets/0bcbc168-d71a-44cf-999f-08c1955f7c0f)

**Comment by TextesAV** [comment]
That's right
