### ISSUE TITLE
spree translations

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#380]
``'%s's blocking spree was ended by %s (%d Kills)``
``'%s's killing spree was ended by %s (%d Kills)``
``%s is on a blocking spree with %d kills!``
``%s is on a killing spree with %d kills!``

**Comment by TextesAV** [comment]
1. Блокирующий беспредел %s был прекращён %s (%d убийств).


2. Убийственная серия %s была остановлена %s (%d убийств).


3. %s в блокирующем беспределе с %d убийствами!


4. %s в убийственной серии с %d убийствами!

**Comment by ChillerDragon** [comment]
@TextesAV is it possible to translate "spree" with the same word twice?

because actually it is

``'%s's [placeholder] spree was ended by %s (%d Kills)``

**Comment by ChillerDragon** [comment]
Does ``блокирующем серии`` work?

**Comment by ChillerDragon** [comment]
Could you also translate ``%d players needed to start a spree.``

**Comment by TextesAV** [comment]
> Does `блокирующем серии` work?

Ye

**Comment by TextesAV** [comment]
> Could you also translate `%d players needed to start a spree.`

Для начала серии нужно %d игроков.

**Comment by TextesAV** [comment]
> @TextesAV is it possible to translate "spree" with the same word twice?
> 
> because actually it is
> 
> `'%s's [placeholder] spree was ended by %s (%d Kills)`

Ye

**Comment by TextesAV** [comment]
> 1. Блокирующий беспредел %s был прекращён %s (%d убийств).
> 2. Убийственная серия %s была остановлена %s (%d убийств).
> 3. %s в блокирующем беспределе с %d убийствами!
> 4. %s в убийственной серии с %d убийствами!

New
1. Блокирующая серия %s была прервана %s (%d убийств).


2. Убийственная серия %s была прервана %s (%d убийств).


3. %s в блокирующей серии с %d убийствами!


4. %s в убийственной серии с %d убийствами!
