### ISSUE TITLE
Filter reconnect spam automatically

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#398]
Frequent and short reconnects should be detected and some anti flood mode should turn on automatically.
If the anti flood mode is on the "joined the game" message is delayed for a few seconds and also requires the player to move at least once. The disconnect message is only sent if the join message was sent. This way bots and players just spamming reconnect are not shown in chat but actual players that stay are properly announced in the chat.

**Comment by fokkonaut** [comment]
There is a limit already which reduces the amount of connections within a specific time.

Bot creators will simply start sending movement, which will not reduce the issue enough.

**Comment by ChillerDragon** [comment]
> There is a limit already which reduces the amount of connections within a specific time.

I saw annoying chat spam by reconnecting bots. Even if it is every 10 seconds if it is constantly I do not want to see their join and disconnect message.

> Bot creators will simply start sending movement, which will not reduce the issue enough.

So far bot creators have not adapted to the existing protections. That is because it is not a targeted attack. If they spam all servers they wont even notice that it does not work on the 3 small ddnet++ servers.
