### ISSUE TITLE
Fix windows support

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#51]
It is an known issue that the DDNetPP windows support is very bad and servers crash after 5 minutes.
But there is also an problem with the /insta command if the instagib arena is below the normal spawn the tees still spawn at normal spawn even after using the ``/insta fng`` command

**Comment by fokkonaut** [comment]
for me it isnt crashing after 5 min anymore and you automatically join the game after some seconds after you connected xD but ye the support is very bad ._.

**Comment by ChillerDragon** [comment]
Windows debug mode doesn't initialize ints with zero. Thats how the survival game state was set to a random value (not 0) and was detected as running. So everybody joined as spectator. (fixed by c164b13445cc7096cb52ae66fea5ea4f57cb48c6 )

The spawns were a ddnet++ unfreindly defualt. Back then i tried to support maps that used red and blue spawns as normal spawns. But the default is now changed to work with ddnet++ instagib lobby maps.

**Comment by ChillerDragon** [comment]
Fixed the last windows sqlite3 crashbug with 893e4c3135f429c5a808f37762491f18fd266a57
